# Site settings
author: Dylan Crawshaw
title: Freshman Year: A Deep Dive into the World of Web Development
header-img: img/home-bg.png
email: dcrawsh@gmail.com
copyright_name: Dylan Crawshaw
description: > # this means to ignore newlines until "baseurl:"
  Lo-fi Indie Rock 'n' Roll coding 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dcrawsh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
